Repository marrink-lab/vermouth-martinize, pull requests merged in 2022-10, with the labels that each got.

#465 merge eunit and region flag
  bin/martinize2
  vermouth/tests/data/integration_tests/tier-1/EN_chain/README
  vermouth/tests/data/integration_tests/tier-1/EN_chain/aa.pdb
  vermouth/tests/data/integration_tests/tier-1/EN_chain/martinize2/cg.pdb
  vermouth/tests/data/integration_tests/tier-1/EN_chain/martinize2/cg.top
  vermouth/tests/data/integration_tests/tier-1/EN_chain/martinize2/chain_A.ssd
  vermouth/tests/data/integration_tests/tier-1/EN_chain/martinize2/citation
  vermouth/tests/data/integration_tests/tier-1/EN_chain/martinize2/command
  vermouth/tests/data/integration_tests/tier-1/EN_chain/martinize2/molecule_0.itp
  vermouth/tests/data/integration_tests/tier-1/EN_chain/martinize2/screen.output
  vermouth/tests/data/integration_tests/tier-1/EN_region/README
  vermouth/tests/data/integration_tests/tier-1/EN_region/aa.pdb
  vermouth/tests/data/integration_tests/tier-1/EN_region/martinize2/cg.pdb
  vermouth/tests/data/integration_tests/tier-1/EN_region/martinize2/cg.top
  vermouth/tests/data/integration_tests/tier-1/EN_region/martinize2/chain_A.ssd
  vermouth/tests/data/integration_tests/tier-1/EN_region/martinize2/citation
  vermouth/tests/data/integration_tests/tier-1/EN_region/martinize2/command
  vermouth/tests/data/integration_tests/tier-1/EN_region/martinize2/molecule_0.itp
  vermouth/tests/data/integration_tests/tier-1/EN_region/martinize2/screen.output
  vermouth/tests/integration_tests/test_integration.py
Labels: hacktoberfest-accepted, publication

#470 Add citation of M3 small molecules (address issue #468)
  vermouth/data/force_fields/martini3001/citations.bib
  vermouth/data/force_fields/martini3001/small_molecule_martini3.ff
Labels: hacktoberfest-accepted

#473 Update aminoacids.ff
  vermouth/data/force_fields/martini3001/aminoacids.ff
  vermouth/tests/data/integration_tests/tier-1/1mj5-charmm/README
  vermouth/tests/data/integration_tests/tier-1/1mj5-charmm/aa.pdb
  vermouth/tests/data/integration_tests/tier-1/1mj5-charmm/martinize2/cg.pdb
  vermouth/tests/data/integration_tests/tier-1/1mj5-charmm/martinize2/cg.top
  vermouth/tests/data/integration_tests/tier-1/1mj5-charmm/martinize2/chain_.ssd
  vermouth/tests/data/integration_tests/tier-1/1mj5-charmm/martinize2/citation
  vermouth/tests/data/integration_tests/tier-1/1mj5-charmm/martinize2/command
  vermouth/tests/data/integration_tests/tier-1/1mj5-charmm/martinize2/molecule_0.itp
  vermouth/tests/data/integration_tests/tier-1/1mj5-charmm/martinize2/screen.output
  vermouth/tests/data/integration_tests/tier-1/lysozyme_prot/martinize2/cg.pdb
  vermouth/tests/data/integration_tests/tier-1/lysozyme_prot/martinize2/molecule_0.itp
  vermouth/tests/integration_tests/test_integration.py
Labels: hacktoberfest-accepted, hacktoberfest
